services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pencatatan
      - cetak-laporan
      - notif-komunikasi
    networks:
      - inventory

  pencatatan:
    build:
      context: .
    env_file:
      - path: .env
        required: false
    environment:
      APP_NAME: Inventory Laravel
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost
      APP_TIMEZONE: Asia/Jakarta
      APP_KEY: "base64:74S6WazXw28sf4xIFV6GVqMSm1ErYZH8Jaz7pUoqAII="
      DB_CONNECTION: pgsql
      DB_SSLMODE: require
      RUN_MIGRATIONS: "true"
      INVENTORY_SERVICE: pencatatan
    ports:
      - "8001:8000"
    expose:
      - "8000"
    networks:
      - inventory

  cetak-laporan:
    build:
      context: .
    env_file:
      - path: .env
        required: false
    environment:
      APP_NAME: Inventory Laravel
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost
      APP_TIMEZONE: Asia/Jakarta
      APP_KEY: "base64:74S6WazXw28sf4xIFV6GVqMSm1ErYZH8Jaz7pUoqAII="
      DB_CONNECTION: pgsql
      DB_SSLMODE: require
      RUN_MIGRATIONS: "false"
      INVENTORY_SERVICE: cetak-laporan
    ports:
      - "8002:8000"
    expose:
      - "8000"
    depends_on:
      - pencatatan
    networks:
      - inventory

  notif-komunikasi:
    build:
      context: .
    env_file:
      - path: .env
        required: false
    environment:
      APP_NAME: Inventory Laravel
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost
      APP_TIMEZONE: Asia/Jakarta
      APP_KEY: "base64:74S6WazXw28sf4xIFV6GVqMSm1ErYZH8Jaz7pUoqAII="
      DB_CONNECTION: pgsql
      DB_SSLMODE: require
      RUN_MIGRATIONS: "false"
      INVENTORY_SERVICE: notif-komunikasi
    ports:
      - "8003:8000"
    expose:
      - "8000"
    depends_on:
      - pencatatan
    networks:
      - inventory

networks:
  inventory:
    driver: bridge
